const siteConfig = {
  brand: {
    name: "51VIPAI",
    subtitle: "个人投资与 AI 知识库",
    logoImage: "",
  },
  socialLinks: [
    { label: "X / Twitter", shortLabel: "X", icon: "x", url: "#" },
    { label: "YouTube", shortLabel: "YT", icon: "youtube", url: "#" },
    { label: "Telegram", shortLabel: "TG", icon: "telegram", url: "#" },
    { label: "微信公众号", shortLabel: "微信", icon: "wechat", url: "#" },
    { label: "小红书", shortLabel: "小红书", icon: "xiaohongshu", url: "#" },
    {
      label: "邮箱联系",
      shortLabel: "@",
      icon: "email",
      url: "mailto:hello@51vipai.com",
    },
  ],
  quickLinks: [
    { label: "每日市场观察", url: "#" },
    { label: "AI 工具笔记", url: "#" },
    { label: "加密货币入门", url: "#" },
    { label: "知识路线图", url: "#" },
  ],
};

const categories = {
  "us-stocks": {
    title: "美股",
    articles: [
      {
        title: "美股新手第一课：先看懂指数、公司和 ETF",
        summary: "用最小知识地图理解美股市场，不急着买入，先建立观察框架。",
        tag: "新手入门",
        date: "2026.08.18",
        image: "",
        url: "articles/us-stocks-beginner.html",
        large: true,
      },
      {
        title: "每日市场观察模板",
        summary: "记录指数、利率、美元、行业轮动和重点公司新闻。",
        tag: "市场观察",
        date: "待添加",
        image: "",
        url: "#",
      },
      {
        title: "财报笔记怎么写",
        summary: "收入、利润、现金流、指引和估值，是拆财报的五个入口。",
        tag: "公司研究",
        date: "待添加",
        image: "",
        url: "#",
      },
    ],
  },
  ai: {
    title: "AI",
    articles: [
      {
        title: "AI 工具地图：从使用者到创造者",
        summary: "整理常用 AI 工具、Agent、模型和工作流，形成自己的工具箱。",
        tag: "AI 工具",
        date: "2026.08.18",
        image: "",
        url: "articles/ai-tools-map.html",
        large: true,
      },
      {
        title: "AI 产业链入门",
        summary: "从芯片、云、模型、应用四层理解 AI 产业。",
        tag: "产业链",
        date: "待添加",
        image: "",
        url: "#",
      },
      {
        title: "我的 AI 学习路线",
        summary: "把概念、实践、项目和投资观察串成一条路线。",
        tag: "路线图",
        date: "待添加",
        image: "",
        url: "#",
      },
    ],
  },
  crypto: {
    title: "加密货币",
    articles: [
      {
        title: "加密货币入门：先理解资产、钱包和交易所",
        summary: "不从价格开始，而是从资产安全、链上转账和风险边界开始。",
        tag: "新手入门",
        date: "2026.08.18",
        image: "",
        url: "articles/crypto-beginner.html",
        large: true,
      },
      {
        title: "比特币观察清单",
        summary: "价格、ETF、链上数据、宏观流动性和政策变化。",
        tag: "BTC",
        date: "待添加",
        image: "",
        url: "#",
      },
      {
        title: "钱包安全笔记",
        summary: "助记词、硬件钱包、授权管理和常见骗局。",
        tag: "安全",
        date: "待添加",
        image: "",
        url: "#",
      },
    ],
  },
  knowledge: {
    title: "知识分享",
    articles: [
      {
        title: "如何搭建自己的知识库",
        summary: "把碎片信息整理成主题、标签、索引和可复用的文章。",
        tag: "方法论",
        date: "2026.08.18",
        image: "",
        url: "articles/how-to-build-knowledge-base.html",
        large: true,
      },
      {
        title: "阅读笔记模板",
        summary: "用问题、证据、结论、行动四步整理一本书或一篇文章。",
        tag: "阅读",
        date: "待添加",
        image: "",
        url: "#",
      },
      {
        title: "个人成长复盘",
        summary: "记录目标、行动、反馈和下一步改进。",
        tag: "成长",
        date: "待添加",
        image: "",
        url: "#",
      },
    ],
  },
  tools: {
    title: "实用工具",
    articles: [
      {
        title: "我的投资工具箱",
        summary: "记录常用网站、数据源、券商工具、AI 工具和自动化流程。",
        tag: "导航",
        date: "2026.08.18",
        image: "",
        url: "#",
        large: true,
      },
      {
        title: "常用数据源清单",
        summary: "按行情、财报、宏观、产业链和新闻来源分类。",
        tag: "数据源",
        date: "待添加",
        image: "",
        url: "#",
      },
      {
        title: "AI 写作辅助流程",
        summary: "从资料收集、提纲、初稿、校对到发布。",
        tag: "效率",
        date: "待添加",
        image: "",
        url: "#",
      },
    ],
  },
  about: {
    title: "关于",
    articles: [
      {
        title: "关于 51VIPAI",
        summary: "这里是一个普通人持续学习投资、AI 与数字世界的公开记录。",
        tag: "关于本站",
        date: "2026.08.18",
        image: "",
        url: "#",
        large: true,
      },
      {
        title: "联系与合作",
        summary: "这里可以放邮箱、社群入口、公众号和其他平台链接。",
        tag: "联系",
        date: "待添加",
        image: "",
        url: "#",
      },
      {
        title: "免责声明",
        summary: "所有内容仅供学习交流，不构成投资建议。",
        tag: "声明",
        date: "待添加",
        image: "",
        url: "#",
      },
    ],
  },
};
